[package]
name = "hello_struct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
flate2 = "1.0.3"
priority-queue = "1.2.1"
stopwatch = "0.0.7"